const IS_DEVELOP = process.env.NODE_ENV === 'development';

export const MOCK_USER = IS_DEVELOP;
export const LOG_REDUX_ACTIONS = IS_DEVELOP;

export const LOADING_TASK_SEARCH_PARTIES = 'SEARCH_PARTIES';
export const LOADING_TASK_SEARCH_PARTY = 'SEARCH_PARTY';
export const LOADING_TASK_SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const LOADING_TASK_TOKEN_EXCHANGE = 'TOKEN_EXCHANGE';
export const LOADING_TASK_FETCH_PRODUCT_ROLES = 'FETCH_PRODUCT_ROLES';
export const LOADING_TASK_UPDATE_PARTY_USER_STATUS = 'UPDATE_PARTY_USER_STATUS';
export const LOADING_TASK_FETCH_USER_PRODUCT = 'FETCH_USER_PRODUCT';
export const LOADING_TASK_SAVE_GROUP = 'SAVE_GROUP';
export const LOADING_TASK_FETCH_PARTY_GROUP = 'FETCH_PARTY_GROUP';
export const LOADING_TASK_FETCH_PARTY_GROUPS = 'FETCH_PARTY_GROUPS';
export const LOADING_TASK_ACTION_ON_PARTY_GROUP = 'ACTION_ON_PARTY_GROUP';
